### ISSUE TITLE
Fresh build meteor errors

### ISSUE THREAD

**Issue by brentkirkland** [melonproject/portal#15]
On a clean build on Ubuntu 14.04 the following error occurs after meteor: 

```
W20170318-19:07:06.524(-7)? (STDERR) /home/brentkirkland/portal/.meteor/local/build/programs/server/boot.js:356
W20170318-19:07:06.524(-7)? (STDERR) }).run();
W20170318-19:07:06.524(-7)? (STDERR)    ^
W20170318-19:07:06.525(-7)? (STDERR) 
W20170318-19:07:06.525(-7)? (STDERR) Error: Cannot find module '../core-js/symbol/iterator'
W20170318-19:07:06.525(-7)? (STDERR)     at require (packages/modules-runtime.js:123:19)
W20170318-19:07:06.525(-7)? (STDERR)     at meteorInstall.node_modules.babel-runtime.helpers.typeof.js (packages/modules.js:8560:17)
W20170318-19:07:06.525(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170318-19:07:06.525(-7)? (STDERR)     at require (packages/modules-runtime.js:120:16)
W20170318-19:07:06.525(-7)? (STDERR)     at meteorInstall.node_modules.meteor.minimongo.selector.js (/home/brentkirkland/portal/.meteor/local/build/programs/server/packages/minimongo.js:1254:16)
W20170318-19:07:06.525(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170318-19:07:06.525(-7)? (STDERR)     at require (packages/modules-runtime.js:120:16)
W20170318-19:07:06.526(-7)? (STDERR)     at /home/brentkirkland/portal/.meteor/local/build/programs/server/packages/minimongo.js:4122:1
W20170318-19:07:06.526(-7)? (STDERR)     at /home/brentkirkland/portal/.meteor/local/build/programs/server/packages/minimongo.js:4145:3
W20170318-19:07:06.526(-7)? (STDERR)     at /home/brentkirkland/portal/.meteor/local/build/programs/server/boot.js:303:34
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

This is a babel error. Going to look into this. If anyone has info please let me know. In the mean time I will look for a solution.

**Comment by brentkirkland** [comment]
`meteor npm install babel-runtime --save`
removes this error but generates the following:

```
W20170318-19:13:52.640(-7)? (STDERR) ReferenceError: Npm is not defined
W20170318-19:13:52.640(-7)? (STDERR)     at Object.<anonymous> (/home/brentkirkland/portal/node_modules/truffle-contract/node_modules/web3/lib/web3/httpprovider.js:34:22)
W20170318-19:13:52.640(-7)? (STDERR)     at Module._compile (module.js:409:26)
W20170318-19:13:52.640(-7)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20170318-19:13:52.640(-7)? (STDERR)     at Module.load (module.js:343:32)
W20170318-19:13:52.640(-7)? (STDERR)     at Function.Module._load (module.js:300:12)
W20170318-19:13:52.640(-7)? (STDERR)     at Module.require (module.js:353:17)
W20170318-19:13:52.641(-7)? (STDERR)     at require (internal/module.js:12:17)
W20170318-19:13:52.641(-7)? (STDERR)     at Object.<anonymous> (/home/brentkirkland/portal/node_modules/truffle-contract/node_modules/web3/lib/web3.js:42:20)
W20170318-19:13:52.641(-7)? (STDERR)     at Module._compile (module.js:409:26)
W20170318-19:13:52.641(-7)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
```
Going to keep digging.

**Comment by brentkirkland** [comment]
Ok, this error is removed if you update the node module truffle-contracts to 0.18.2. (I'm going to leave them an issue). 

But this uncovers a new error (yay!):

```
W20170318-19:53:25.955(-7)? (STDERR) /home/brentkirkland/.meteor/packages/meteor-tool/.1.4.3_2.1r6il64++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170318-19:53:25.955(-7)? (STDERR) 						throw(ex);
W20170318-19:53:25.956(-7)? (STDERR) 						^
W20170318-19:53:25.956(-7)? (STDERR) 
W20170318-19:53:25.956(-7)? (STDERR) TypeError: Universe.setProvider is not a function
W20170318-19:53:25.956(-7)? (STDERR)     at meteorInstall.imports.api.assets.js (imports/api/assets.js:9:10)
W20170318-19:53:25.956(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170318-19:53:25.956(-7)? (STDERR)     at Module.require (packages/modules-runtime.js:120:16)
W20170318-19:53:25.956(-7)? (STDERR)     at Module.Mp.import (/home/brentkirkland/.meteor/packages/modules/.0.7.9.1cswflq++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:75:16)
W20170318-19:53:25.956(-7)? (STDERR)     at meteorInstall.imports.startup.server.register-apis.js (imports/startup/server/register-apis.js:1:166)
W20170318-19:53:25.956(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
W20170318-19:53:25.956(-7)? (STDERR)     at Module.require (packages/modules-runtime.js:120:16)
W20170318-19:53:25.957(-7)? (STDERR)     at Module.Mp.import (/home/brentkirkland/.meteor/packages/modules/.0.7.9.1cswflq++os+web.browser+web.cordova/npm/node_modules/reify/lib/runtime.js:75:16)
W20170318-19:53:25.957(-7)? (STDERR)     at meteorInstall.imports.startup.server.index.js (imports/startup/server/index.js:1:98)
W20170318-19:53:25.957(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:197:9)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
```

And it's true, there is Universe.setProvider is not a function. Care to explain what's going on here?

**Comment by retotrinkler** [comment]
Hi Bernt,
Just upgraded contracts from truffle 3.0.0-9 t0 3.1.9 which aren't integrated/properly handled yet - should be fixed v soon

**Comment by brentkirkland** [comment]
Great to hear!

But going back to my last comment. Where is this setProvider function? 
I'm trying to understand why a json file is being used as what seems to be a store. This seems odd...

Seems like a good place to adapt Redux.

**Comment by retotrinkler** [comment]
This setProvider comes from a truffle 'build' in truffle v3.0.0-9 by using the command line commnad
```
$ truffle migrate
```
truffle used to bundle files inte `*.sol.js` files which contain these `setProvider` functions example [here](https://github.com/melonproject/portal/blob/88531193a4bd30145709a91aa817570292a4dbdd/imports/lib/assets/contracts/Asset.sol.js#L226)

**Comment by retotrinkler** [comment]
actually am just trying to figure out how to best solve this. 
kind of would like to try [parity.js](https://www.npmjs.com/package/@parity/parity.js) for all server-side web3 interactions
**advantages**
- v light package compared to `truffle-contract`
- Promise-based

**disadvantages**
- as far as I know not compatible with mist and/or metamaks, i.e. when user want to interact w web3 mist or metamask signer would not be prompted

**Comment by retotrinkler** [comment]
am not really familiar w `Redux` can one integrate Redux into Meteor environment?

**Comment by retotrinkler** [comment]
but heard lots of good things about Redux, is there any reading up material you'd recommend?

**Comment by brentkirkland** [comment]
Ahhh I see. My miss understanding. 

Yes you can integrate redux into meteor. The reading material that helped me understand is the official documentation. http://redux.js.org/docs/basics/

It's complicated at first, but I would be willing to help you integrate. I think it's the most clean way of storing data.

**Comment by travs** [comment]
Just wanted to register that I receive the same error as in [Brent's second post](https://github.com/melonproject/portal/issues/15#issuecomment-287589137) on a fresh install in OSX Sierra.

**Comment by retotrinkler** [comment]
Hi, thanks for letting me know!
Did
```
$ meteor npm install babel-runtime --save
``` 
resolve the error?

**Comment by retotrinkler** [comment]
am going to close this one.. should this issue persist please let me know
